# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: MoNA
# Description of the Site
description: The Mobile Network Analyzer
# URL of Image of the Site
site-image: assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://raw.githubusercontent.com/Forensic-Science-Investigation-Lab/mona/main/docs/assets/images/heroimage.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: spranger@hs-mittweida.de
#facebook_username: /
#twitter_username: /
instagram_username: forensik.studyweida
#linkedin_username: /
#github_username:  Forensic-Science-Investigation-Lab
#youtube_channel_id: /
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
#google-analytics:

# Disqus
#disqus-shortname:

# Name of the Author
author-name: Michael Spranger
# URL for the Image of the Author
author-image: /
# 60 Words About the Author
author-about: With MoNA, we present a platform for analysing mobile communication developed at Mittweida University of Applied Sciences in collaboration with various LEAs. MoNA integrates highly specialised AI services to support deep semantic analysis of communications across different channels and involving different modalities, such as video, images, audio, etc. The aim is to reduce the investigator's effort in searching for evidential information in networks. The core services such as Topic Modeling, Term Tree (Contextual Pattern Matcher), Author Profiling or Search Term Recommender are completely unsupervised, i.e. the analysis is based solely on data and no additional training is required.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: mailto:spranger@hs-mittweida.de

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "tutorials/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
